M48
; DRILL file {KiCad (6.0.7)} date Sat Sep 24 21:41:40 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-24T21:41:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.6289Y-4.1917
X4.8199Y-4.1917
T2
X4.6171Y-4.311
X4.8317Y-4.311
T3
X3.9567Y-1.9488
X3.9567Y-4.2717
X5.4921Y-1.9488
X5.4921Y-4.2717
T0
M30
